providers = ["node"]

[variables]
NODE_VERSION = "20"

[phases.install]
cmds = [
  "npm install -g corepack",
  "corepack enable",
  "corepack prepare pnpm@9.1.0 --activate",
  "pnpm install --no-frozen-lockfile"
]
# Esto le dice a Railway: "No ejecutes tu propia instalación después de mis comandos"
onlyIncludeFiles = ["package.json", "pnpm-lock.yaml"] 

[phases.build]
cmds = ["pnpm run build"]