# Esto va arriba de todo para que Nixpacks sepa qué archivos vigilar
onlyIncludeFiles = ["package.json", "pnpm-lock.yaml"]

providers = ["node"]

[variables]
NODE_VERSION = "20"

[phases.install]
cmds = [
  "npm install -g corepack",
  "corepack enable",
  "corepack prepare pnpm@9.1.0 --activate",
  "pnpm install --no-frozen-lockfile --only-built-dependencies=esbuild,@swc/core,msw"
]

[phases.build]
cmds = ["pnpm run build"]